package com.dragonfly.talkingclock.ui.theme

import androidx.compose.ui.graphics.Color

val LightPrimary = Color(0xFF4A43B4)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFE1DFFF)
val LightOnPrimaryContainer = Color(0xFF100568)
val LightSecondary = Color(0xFF006B5B)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFF7DF2C3)
val LightOnSecondaryContainer = Color(0xFF00201A)
val LightTertiary = Color(0xFF7C556D)
val LightBackground = Color(0xFFFCF8FF)
val LightOnBackground = Color(0xFF1C1B22)
val LightSurface = Color(0xFFFCF8FF)
val LightOnSurface = Color(0xFF1C1B22)
val LightSurfaceVariant = Color(0xFFE5E1EC)
val LightOnSurfaceVariant = Color(0xFF48454F)
val LightError = Color(0xFFBA1A1A)

val DarkPrimary = Color(0xFFC4C0FF)
val DarkOnPrimary = Color(0xFF1A1095)
val DarkPrimaryContainer = Color(0xFF332A9B)
val DarkOnPrimaryContainer = Color(0xFFE1DFFF)
val DarkSecondary = Color(0xFF60D6A8)
val DarkOnSecondary = Color(0xFF00382D)
val DarkSecondaryContainer = Color(0xFF005143)
val DarkOnSecondaryContainer = Color(0xFF7DF2C3)
val DarkTertiary = Color(0xFFEDB9D3)
val DarkBackground = Color(0xFF14131A)
val DarkOnBackground = Color(0xFFE5E1EC)
val DarkSurface = Color(0xFF14131A)
val DarkOnSurface = Color(0xFFE5E1EC)
val DarkSurfaceVariant = Color(0xFF48454F)
val DarkOnSurfaceVariant = Color(0xFFC9C5D0)
val DarkError = Color(0xFFFFB4AB)
